### ISSUE TITLE
Access to Typebox in the editor

### ISSUE THREAD

**Issue by Dyskal** [sinclairzx81/typebox-workbench#13]
Hey,
I am working with complex types and trying to migrate them to Typebox, i wanted to copy my Typebox types and objects definition in the editor but I can't manage to import Typebox in the editor.
Could you help me ? Or provide a way to make at least Type and Static works?
Thanks.

**Comment by sinclairzx81** [comment]
@Dyskal Hi, sorry about the delay in reply.

This project is primary focused on TS -> Runtime Type System generation, and doesn't really have the infrastructure setup to accept TypeBox types directly (not without a lot of overhauling the current UI). However with this said, you might be able to get some use from https://github.com/sinclairzx81/typebox-codegen which is the backend for the Workbench and provides some programmatic access to the code generators.

Will close off this issue for now as there are no immediate plans to support editing TB types in the Workbench (you can only generate them from TypeScript)

All the best
S
