### ISSUE TITLE
Getting transform-error for object with @ in the field name

### ISSUE THREAD

**Issue by JLarky** [sinclairzx81/typebox-workbench#14]
I noticed a bug with objects that have special characters like `@` in this case where the app will get into state where only a couple of options work, but valibot/zod and TS will give `transform-error`

Here's an example of such input:

```
type X = {
  "@type": string
}
```

**Comment by sinclairzx81** [comment]
@JLarky Hi, Thanks for reporting (and sorry about the delay)

I've applied a fix for this and republished the Workbench site. The fix has also been applied to https://github.com/sinclairzx81/typebox-codegen on 0.10.1. You can test the fix at the link below.

[Workbench Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=dHlwZSBYID0gewogICJAdHlwZSI6IHN0cmluZwp9)

Will close off this issue for now.
Cheers!
S
