### ISSUE TITLE
Update Yrel to v2

### ISSUE THREAD

**Issue by romelperez** [sinclairzx81/typebox-workbench#2]
Hey @sinclairzx81!

The package [`yrel`](https://github.com/romelperez/yrel) is now in version 2 with a few breaking changes and new features.

Remarkably:

- Rename `v` to `y`.
- Rename `validate` to `validateYrel`.
- Rename `InferDataSchemaType` to `InferYrel`.
- Rename most types with the prefix of `Yrel` instead of `Data`.
- Add `y.record(key: YrelSchemaString, value: YrelSchema): YrelSchemaRecord` for `Record<string, InferYrel<typeof value>>`.
- Add pre-processors support with `.preprocess(preprocessor)`.
- Add `.coerce()` for primitive schemas.
- Add transformers support with `.transform(transformer)`.
- Add default values support with `.defaultsTo(value)`.

And a few more minor features and bugfixes.

Let me know if I can help!

**Comment by sinclairzx81** [comment]
@romelperez Hiya,

Apologies for the delay on this. Have bumped `yrel` to `2.1.6` and fixed up the breaking interface changes from the previous version.

Changes Include:

- Rename `v` to `y`
- Rename `InferDataSchemaType` to `InferYrel`
- Added additional type `y.record(key, value)` (supported for string keys only)

Will close off this issue for now, and again sorry for the delay (this project gets fairly low priority)
All the best
S

**Comment by romelperez** [comment]
Hey @sinclairzx81 , awesome, thank you very much! 🙌
