### ISSUE TITLE
Translate schema to other library

### ISSUE THREAD

**Issue by fabian-hiller** [sinclairzx81/typebox-workbench#3]
Is it technically possible to automatically translate a Zod schema into a Valibot schema? This would be a very useful feature for us.

**Comment by sinclairzx81** [comment]
@fabian-hiller Hiya,

It is technically possible to transform one library into another, however this project would only be interested in supporting auxiliary library transforms if each library were to adopt a common runtime type representation (i.e. like Json Schema). This is because direct library to library transformations would require too much internal knowledge of each library (so not willing to support that), but would certainly explore transformations based on a common intermediate representation (if libraries were to adopt one)

TypeBox defaultly uses Json Schema for it's type representation (industry spec, interoperable, etc), and all the current transforms here are based on remapping the TypeBox [Json Schema Subset](https://github.com/sinclairzx81/typebox#json-types) out to each library. 

As a starter (and if you wanted to explore library transforms). The following code transforms Zod into Valibot through TypeBox's Json Schema representation. You can either update this code to be `ZodToValibot` (direct library to library, so may suit your use case), or have a look at producing a `ValibotToTypeBox` similar to below. If you were to implement a `ValibotToTypeBox`, I would investigate integrating both on the Workbench.

```bash
$ npm install zod @sinclair/typebox @sinclair/typebox-codegen
```


```typescript
import { ModelToValibot, TypeBoxModel } from '@sinclair/typebox-codegen'
import { Type } from '@sinclair/typebox'
import z from 'zod'

export namespace ZodToTypeBox {
  function TAny(type: z.ZodAny) {
    return Type.Any()
  }
  function TArray(type: z.ZodArray<z.ZodTypeAny>) {
    return Type.Array(Visit(type._def.type))
  }
  function TString(type: z.ZodString) {
    const maxLength = type.maxLength !== null ? { maxLength: type.maxLength } : {}
    const minLength = type.minLength !== null ? { minLength: type.minLength } : {}
    return Type.String({ ...maxLength, ...minLength })
  }
  function TNumber(type: z.ZodNumber) {
    const maximum = type.maxValue !== null ? { maximum: type.maxValue } : {}
    const minimum = type.minValue !== null ? { minimum: type.minValue } : {}
    return Type.Number({ ...maximum, ...minimum })
  }
  function TBoolean(type: z.ZodBoolean) {
    return Type.Boolean()
  }
  function TBigInt(type: z.ZodBigInt) {
    return Type.BigInt()
  }
  function TNull(type: z.ZodNull) {
    return Type.Null()
  }
  function TUndefined(type: z.ZodUndefined) {
    return Type.Undefined()
  }
  function TUnknown(type: z.ZodUnknown) {
    return Type.Unknown()
  }
  function TObject(type: z.ZodObject<z.ZodRawShape>) {
    const shape = type._def.shape()
    const keys = Object.keys(shape)
    const properties = keys.reduce((acc, key) => ({ ...acc, [key]: Visit(shape[key]) }), {})
    return Type.Object(properties)
  }
  function TUnion(type: z.ZodUnion<readonly [z.ZodTypeAny, ...z.ZodTypeAny[]]>) {
    return Type.Union(type.options.map(type => Visit(type)))
  }
  function TIntersect(type: z.ZodIntersection<z.ZodTypeAny, z.ZodTypeAny>) {
    return Type.Intersect([Visit(type._def.left), Visit(type._def.right)])
  }
  function TTuple(type: z.ZodTuple<[z.ZodTypeAny, ...z.ZodTypeAny[]]>) {
    return Type.Tuple(type._def.items.map(type => Visit(type)))
  }
  function TUnsupported(type: z.ZodTypeAny) {
    return Type.Any({ description: 'unsupported' })
  }
  function Visit(type: z.ZodTypeAny) {
    return (
      (type instanceof z.ZodAny) ? TAny(type) :
      (type instanceof z.ZodArray) ? TArray(type) :
      (type instanceof z.ZodString) ? TString(type) : 
      (type instanceof z.ZodNumber) ? TNumber(type) :
      (type instanceof z.ZodBoolean) ? TBoolean(type) :
      (type instanceof z.ZodBigInt) ? TBigInt(type) :
      (type instanceof z.ZodNull) ? TNull(type) :
      (type instanceof z.ZodUndefined) ? TUndefined(type) :
      (type instanceof z.ZodObject) ? TObject(type) :
      (type instanceof z.ZodUnion) ? TUnion(type) :
      (type instanceof z.ZodIntersection) ? TIntersect(type) :
      (type instanceof z.ZodTuple) ? TTuple(type) :
      (type instanceof z.ZodUnknown) ? TUnknown(type) :
      TUnsupported(type)
    )
  }
  export function Transform(type: z.ZodTypeAny) {
    return Visit(type)
  }
}
// -------------------------------------------------------
// Zod To TypeBox
// -------------------------------------------------------
const T = ZodToTypeBox.Transform(z.object({
  x: z.number(),
  y: z.number(),
  z: z.number()
}))

// -------------------------------------------------------
// TypeBox To Valibot
// -------------------------------------------------------
const O = ModelToValibot.Generate({
  types: [{ ...T, $id: 'T' }]
} as TypeBoxModel)

console.log(O)

// import * as v from 'valibot'

// export type T = v.Output<typeof T>
// export const T = v.object({
//   x: v.number(),
//   y: v.number(),
//   z: v.number()
// })
```
Hope this helps!
Cheers
S

**Comment by fabian-hiller** [comment]
Thank you very much! I understand. Since the main feature of Valibot is the bundle size, a representation like JSON Schema does not work for us. But in principle I can imagine to offer such an implementation under `import {…} from 'valibot/json';` with the same API design as an alternative in the future.

I think most Valibot users come from Zod and would love to be able to convert their existing schemas automatically. I would be happy to include or link to such a tool in our docs.

**Comment by sinclairzx81** [comment]
@fabian-hiller Heya,

Going to close off this issue as there isn't much to action at this stage. I may look into Library to Library transformations in the future, but again, would prefer to operate from an (IR) intermediate representation (be it Json Schema or something else) as this is much easier to map for. 

May take look at mapping Zod, Valibot, Ark into an IR when I get a bit of free time (and weigh up the maintenance cost). At this point in time, I'm not sure how feasible it will be (as library internals can change, but reading internals (reflection) is required for IR generation) and don't want to maintain mappings for other peoples libraries if there is a huge maintenance cost, but picking a stable version of each library and mapping from there may be feasible, we'll see.

Will close off for now tho.

All the best
S

**Comment by fabian-hiller** [comment]
Hi, I totally understand you! Thanks for the feedback. In the long term, I would be interested in an exchange with you.
