### ISSUE TITLE
Support flat export interface

### ISSUE THREAD

**Issue by wenerme** [sinclairzx81/typebox-workbench#5]
e.g.

```ts
export type BaseResource = {
  id: string;
  uid: string;
  eid: string;
  rid?: string;
  cid?: string;
  tid?: string;

  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;

  attributes?: Record<string, any>;
  properties?: Record<string, any>;
  extensions?: Record<string, any>;
};

interface HasCustomer {
  contactId?: string;
  accountId?: string;
  customerId?: string;
  customerType?: string;

  contact?: BaseResource;
  account?: BaseResource;
}

interface HasStatus {
  state: string;
  status: string;
}

interface HasOwner {
  ownerId?: string;
  ownerType?: string;
  ownerUserId?: string;
  ownerTeamId?: string;
  ownerUser?: BaseResource;
  ownerTeam?: BaseResource;
}

interface Auditable {
  createdById?: string;
  updatedById?: string;
  deletedById?: string;
}

interface CustomerStatefulResource extends BaseResource, HasOwner, HasCustomer, HasStatus {}

export interface LeadResource extends BaseResource, HasCustomer, HasStatus {
  title: string;
  description?: string;
  remark?: string;
  customerRequest?: string;
  contactName?: string;
  contactPhone?: string;
}
```

I want to get a `TObject` instead of `TIntersect` with `allOf`

**Comment by sinclairzx81** [comment]
@wenerme Heya,

Ok, have pushed a mapping change to resolve for this case. I've replaced `Intersect` with `Composite` which will produce a flat `TObject`. I'm also using `Composite` for the extends heritage list. I think TypeBox could maybe provide a better mapping option for this kind of structure, however at this point in time, the closest approximation is Composite (just be mindful that Composite will intersect overlapping properties in the base type)

[Workbench Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=ZXhwb3J0IHR5cGUgQmFzZVJlc291cmNlID0gewogIGlkOiBzdHJpbmc7CiAgdWlkOiBzdHJpbmc7CiAgZWlkOiBzdHJpbmc7CiAgcmlkPzogc3RyaW5nOwogIGNpZD86IHN0cmluZzsKICB0aWQ%2FOiBzdHJpbmc7CgogIGNyZWF0ZWRBdDogRGF0ZSB8IHN0cmluZzsKICB1cGRhdGVkQXQ6IERhdGUgfCBzdHJpbmc7CiAgZGVsZXRlZEF0PzogRGF0ZSB8IHN0cmluZzsKCiAgYXR0cmlidXRlcz86IFJlY29yZDxzdHJpbmcsIGFueT47CiAgcHJvcGVydGllcz86IFJlY29yZDxzdHJpbmcsIGFueT47CiAgZXh0ZW5zaW9ucz86IFJlY29yZDxzdHJpbmcsIGFueT47Cn07CgppbnRlcmZhY2UgSGFzQ3VzdG9tZXIgewogIGNvbnRhY3RJZD86IHN0cmluZzsKICBhY2NvdW50SWQ%2FOiBzdHJpbmc7CiAgY3VzdG9tZXJJZD86IHN0cmluZzsKICBjdXN0b21lclR5cGU%2FOiBzdHJpbmc7CgogIGNvbnRhY3Q%2FOiBCYXNlUmVzb3VyY2U7CiAgYWNjb3VudD86IEJhc2VSZXNvdXJjZTsKfQoKaW50ZXJmYWNlIEhhc1N0YXR1cyB7CiAgc3RhdGU6IHN0cmluZzsKICBzdGF0dXM6IHN0cmluZzsKfQoKaW50ZXJmYWNlIEhhc093bmVyIHsKICBvd25lcklkPzogc3RyaW5nOwogIG93bmVyVHlwZT86IHN0cmluZzsKICBvd25lclVzZXJJZD86IHN0cmluZzsKICBvd25lclRlYW1JZD86IHN0cmluZzsKICBvd25lclVzZXI%2FOiBCYXNlUmVzb3VyY2U7CiAgb3duZXJUZWFtPzogQmFzZVJlc291cmNlOwp9CgppbnRlcmZhY2UgQXVkaXRhYmxlIHsKICBjcmVhdGVkQnlJZD86IHN0cmluZzsKICB1cGRhdGVkQnlJZD86IHN0cmluZzsKICBkZWxldGVkQnlJZD86IHN0cmluZzsKfQoKaW50ZXJmYWNlIEN1c3RvbWVyU3RhdGVmdWxSZXNvdXJjZSBleHRlbmRzIEJhc2VSZXNvdXJjZSwgSGFzT3duZXIsIEhhc0N1c3RvbWVyLCBIYXNTdGF0dXMge30KCmV4cG9ydCBpbnRlcmZhY2UgTGVhZFJlc291cmNlIGV4dGVuZHMgQmFzZVJlc291cmNlLCBIYXNDdXN0b21lciwgSGFzU3RhdHVzIHsKICB0aXRsZTogc3RyaW5nOwogIGRlc2NyaXB0aW9uPzogc3RyaW5nOwogIHJlbWFyaz86IHN0cmluZzsKICBjdXN0b21lclJlcXVlc3Q%2FOiBzdHJpbmc7CiAgY29udGFjdE5hbWU%2FOiBzdHJpbmc7CiAgY29udGFjdFBob25lPzogc3RyaW5nOwp9Cg%3D%3D)

Will close this issue for now
Cheers
S
